//! `manifest.toml` — the wire contract between `mitos-build`,
//! `mitos-cli upload-module`, and the host's `/_admin/modules/{id}`
//! endpoint.
//!
//! See `MITOS_PLATFORM_DEPLOYMENT.md` for the design rationale.
//! The manifest is auto-generated by `mitos-build` (via dry-load
//! through wasmtime); never hand-edited.
//!
//! Living in `mitos-platform` for v1; will move to a
//! `mitos-protocol::deploy` shared types crate when the build
//! tool lands so all three sides depend on one definition (the
//! mirror-types-drift problem the bank-of-lessons-learned flags).

use serde::{Deserialize, Serialize};

/// Top-level manifest written by `mitos-build`. Lossless TOML
/// round-trip: serialise → deserialise yields the same struct.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Manifest {
    pub module: ModuleSection,
    pub abi: AbiSection,
    pub trap_policy: TrapPolicySection,
    pub build: BuildSection,
    /// v2-only: declarative interest set the platform applies
    /// before block dispatch starts. Bootstrapping (current-
    /// state hydration at watched addresses) runs against this
    /// set; runtime mutation via `update-interest` evolves it
    /// from there. Empty / absent for v1 modules — they
    /// declare interest in their config or by other means.
    #[serde(default, skip_serializing_if = "InterestSection::is_empty")]
    pub interest: InterestSection,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct InterestSection {
    /// bech32 addresses to watch + bootstrap. Maps to
    /// `at-address` predicates; bootstrap walks
    /// `utxos_by_address` for each on first deploy.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub addresses: Vec<String>,
    /// 56-char lowercase hex policy ids to watch. Maps to
    /// `holds-policy` predicates; matches outputs whose
    /// asset multiset contains any asset under the policy.
    /// Bootstrap walks `utxos_by_policy` when set.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub policies: Vec<String>,
}

/// Modules that cold-start a newly-subscribed predicate via the
/// budget-safe chunked `rebootstrap` pump (the host drives it after
/// `update-interest` on an Add) rather than the host's inline
/// synthetic bootstrap. These page-oriented modules dropped their
/// inline single-fuel cold-start (which trapped + emitted nothing
/// for large collections) and seed a scoped onboard set instead.
///
/// Hardcoded rather than manifest-driven: the natural home is a
/// manifest `[interest]` flag, but `toml::to_string` drops a trailing
/// nested table whose siblings are empty-skipped, silently losing the
/// flag for exactly these (no static interest) modules. Revisit as a
/// manifest field if the serializer is fixed or the manifest moves to
/// CBOR. Other modules must NOT be listed here — a pump on a module
/// that also cold-starts inline (burn-address) would double-emit.
pub fn is_chunked_cold_start_module(module_id: &str) -> bool {
    matches!(
        module_id,
        "collection-holders" | "collection-metadata" | "holder-distribution" | "vesting-tracker"
    )
}

impl InterestSection {
    pub fn is_empty(&self) -> bool {
        self.addresses.is_empty() && self.policies.is_empty()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ModuleSection {
    pub id: String,
    /// Lowercase hex SHA-256 of the wasm bytes. Host re-computes
    /// + verifies on upload — protects against tampered manifests.
    pub sha256: String,
    pub size_bytes: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AbiSection {
    pub version_major: u32,
    pub version_minor: u32,
    pub wit_package: String,
    pub wit_world: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TrapPolicySection {
    /// One of `replay` | `skip-and-mark` | `quarantine`.
    pub strategy: String,
    pub max_retries: u32,
    pub backoff_cap_ms: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BuildSection {
    pub rust_version: String,
    pub target: String,
    pub profile: String,
    /// RFC 3339 timestamp of when `mitos-build` produced the artifact.
    pub build_id: String,
    /// Optional git SHA from the source tree at build time.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_sha: Option<String>,
    /// Crate version from the source `Cargo.toml`.
    pub crate_version: String,
}

#[derive(Debug, thiserror::Error)]
pub enum ManifestError {
    #[error("manifest TOML parse: {0}")]
    Parse(String),
    #[error(
        "abi version mismatch: host wants {wanted_major}.x, manifest claims {got_major}.{got_minor}"
    )]
    AbiMismatch {
        wanted_major: u32,
        got_major: u32,
        got_minor: u32,
    },
    #[error("wit world mismatch: host wants {wanted}, manifest claims {got}")]
    WitMismatch { wanted: String, got: String },
    #[error("manifest sha256 doesn't match wasm bytes: manifest={manifest}, computed={computed}")]
    ShaMismatch { manifest: String, computed: String },
    #[error("manifest size_bytes doesn't match wasm bytes: manifest={manifest}, actual={actual}")]
    SizeMismatch { manifest: u64, actual: u64 },
    #[error("invalid trap strategy `{0}` — expected replay | skip-and-mark | quarantine")]
    InvalidTrapStrategy(String),
    #[error("invalid module id `{0}` — must be [a-z0-9-]+ (max 64 chars)")]
    InvalidModuleId(String),
}

impl Manifest {
    /// Parse from a TOML string.
    pub fn parse(s: &str) -> Result<Self, ManifestError> {
        toml::from_str(s).map_err(|e| ManifestError::Parse(e.to_string()))
    }

    /// Serialise to TOML.
    pub fn to_toml(&self) -> Result<String, ManifestError> {
        toml::to_string(self).map_err(|e| ManifestError::Parse(e.to_string()))
    }

    /// Validate the manifest against the host's expectations and
    /// against the actual wasm bytes the manifest claims to describe.
    ///
    /// `accepted_abis` is a list of `(major, wit_world)` pairs the
    /// host is willing to load. The unified host accepts both v1
    /// (`(2, "mitos:platform-v2/mitos-module-v2")`) and v2
    /// (`(2, "mitos:platform-v2/mitos-module-v2")`); routing
    /// happens at start time per `manifest.abi.version_major`.
    pub fn validate_against_host(
        &self,
        wasm_bytes: &[u8],
        accepted_abis: &[(u32, &str)],
    ) -> Result<(), ManifestError> {
        validate_module_id(&self.module.id)?;
        validate_trap_strategy(&self.trap_policy.strategy)?;

        // Match (major, wit_world) against the accepted set.
        // Both must align — a manifest claiming v2 major with the
        // v1 world (or vice-versa) is malformed.
        let claimed_world = format!("{}/{}", self.abi.wit_package, self.abi.wit_world);
        let mut matched = false;
        for (major, world) in accepted_abis {
            if self.abi.version_major == *major && claimed_world == *world {
                matched = true;
                break;
            }
        }
        if !matched {
            // Pick the first accepted ABI as the "wanted" hint —
            // the operator gets a clear next-step rather than the
            // full set in the error.
            let (wanted_major, wanted_world) = accepted_abis
                .first()
                .copied()
                .unwrap_or((2, "mitos:platform-v2/mitos-module-v2"));
            // Major mismatch wins as the more informative error
            // when both axes diverge.
            if self.abi.version_major != wanted_major {
                return Err(ManifestError::AbiMismatch {
                    wanted_major,
                    got_major: self.abi.version_major,
                    got_minor: self.abi.version_minor,
                });
            }
            return Err(ManifestError::WitMismatch {
                wanted: wanted_world.to_owned(),
                got: claimed_world,
            });
        }

        // Wasm bytes must hash + size to what the manifest claims.
        let actual_size = wasm_bytes.len() as u64;
        if actual_size != self.module.size_bytes {
            return Err(ManifestError::SizeMismatch {
                manifest: self.module.size_bytes,
                actual: actual_size,
            });
        }

        let computed_sha = sha256_hex(wasm_bytes);
        if computed_sha != self.module.sha256 {
            return Err(ManifestError::ShaMismatch {
                manifest: self.module.sha256.clone(),
                computed: computed_sha,
            });
        }

        Ok(())
    }
}

fn validate_module_id(id: &str) -> Result<(), ManifestError> {
    if id.is_empty() || id.len() > 64 {
        return Err(ManifestError::InvalidModuleId(id.to_owned()));
    }
    let valid = id
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-');
    if !valid {
        return Err(ManifestError::InvalidModuleId(id.to_owned()));
    }
    Ok(())
}

fn validate_trap_strategy(s: &str) -> Result<(), ManifestError> {
    match s {
        "replay" | "skip-and-mark" | "quarantine" => Ok(()),
        _ => Err(ManifestError::InvalidTrapStrategy(s.to_owned())),
    }
}

/// Lowercase hex SHA-256 of the input bytes.
pub fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex::encode(hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample(sha: &str, size: u64) -> Manifest {
        Manifest {
            module: ModuleSection {
                id: "my-indexer".to_owned(),
                sha256: sha.to_owned(),
                size_bytes: size,
            },
            abi: AbiSection {
                version_major: 2,
                version_minor: 0,
                wit_package: "mitos:platform-v2".to_owned(),
                wit_world: "mitos-module-v2".to_owned(),
            },
            trap_policy: TrapPolicySection {
                strategy: "replay".to_owned(),
                max_retries: 3,
                backoff_cap_ms: 1_000,
            },
            build: BuildSection {
                rust_version: "1.95.0".to_owned(),
                target: "wasm32-wasip2".to_owned(),
                profile: "release".to_owned(),
                build_id: "2026-05-03T12:34:00Z".to_owned(),
                git_sha: Some("abc123".to_owned()),
                crate_version: "0.1.0".to_owned(),
            },
            interest: InterestSection::default(),
        }
    }

    #[test]
    fn round_trip_toml() {
        let bytes = b"hello wasm";
        let m = sample(&sha256_hex(bytes), bytes.len() as u64);
        let s = m.to_toml().unwrap();
        let parsed = Manifest::parse(&s).unwrap();
        assert_eq!(m, parsed);
    }

    #[test]
    fn validate_happy_path() {
        let bytes = b"hello wasm";
        let m = sample(&sha256_hex(bytes), bytes.len() as u64);
        m.validate_against_host(bytes, &[(2, "mitos:platform-v2/mitos-module-v2")])
            .unwrap();
    }

    #[test]
    fn validate_abi_mismatch() {
        // Submit a v1 manifest to a v2-only host. Expect rejection
        // — v1 ABI was retired May 2026 and the host's accepted-ABI
        // list no longer carries `(1, "mitos:platform/mitos-module")`.
        let bytes = b"hello wasm";
        let mut m = sample(&sha256_hex(bytes), bytes.len() as u64);
        m.abi.version_major = 1;
        m.abi.wit_package = "mitos:platform".to_owned();
        m.abi.wit_world = "mitos-module".to_owned();
        let err = m
            .validate_against_host(bytes, &[(2, "mitos:platform-v2/mitos-module-v2")])
            .unwrap_err();
        assert!(matches!(err, ManifestError::AbiMismatch { .. }));
    }

    #[test]
    fn validate_wit_mismatch() {
        let bytes = b"hello wasm";
        let mut m = sample(&sha256_hex(bytes), bytes.len() as u64);
        m.abi.wit_package = "wrong:package".to_owned();
        let err = m
            .validate_against_host(bytes, &[(2, "mitos:platform-v2/mitos-module-v2")])
            .unwrap_err();
        assert!(matches!(err, ManifestError::WitMismatch { .. }));
    }

    #[test]
    fn validate_sha_mismatch() {
        let bytes = b"hello wasm";
        let m = sample("00".repeat(32).as_str(), bytes.len() as u64);
        let err = m
            .validate_against_host(bytes, &[(2, "mitos:platform-v2/mitos-module-v2")])
            .unwrap_err();
        assert!(matches!(err, ManifestError::ShaMismatch { .. }));
    }

    #[test]
    fn validate_size_mismatch() {
        let bytes = b"hello wasm";
        let m = sample(&sha256_hex(bytes), 9999);
        let err = m
            .validate_against_host(bytes, &[(2, "mitos:platform-v2/mitos-module-v2")])
            .unwrap_err();
        assert!(matches!(err, ManifestError::SizeMismatch { .. }));
    }

    #[test]
    fn rejects_invalid_module_id() {
        for bad in &[
            "",
            "Foo",
            "has space",
            "../etc/passwd",
            "x".repeat(65).as_str(),
        ] {
            let bytes = b"hello wasm";
            let mut m = sample(&sha256_hex(bytes), bytes.len() as u64);
            m.module.id = (*bad).to_owned();
            let err = m
                .validate_against_host(bytes, &[(2, "mitos:platform-v2/mitos-module-v2")])
                .unwrap_err();
            assert!(
                matches!(err, ManifestError::InvalidModuleId(_)),
                "expected InvalidModuleId for `{bad}`, got {err:?}"
            );
        }
    }

    #[test]
    fn rejects_invalid_trap_strategy() {
        let bytes = b"hello wasm";
        let mut m = sample(&sha256_hex(bytes), bytes.len() as u64);
        m.trap_policy.strategy = "ignore-and-cry".to_owned();
        let err = m
            .validate_against_host(bytes, &[(2, "mitos:platform-v2/mitos-module-v2")])
            .unwrap_err();
        assert!(matches!(err, ManifestError::InvalidTrapStrategy(_)));
    }
}
