[package]
name = "mitos-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dolos-core = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
